// Ported from project/i18n.js — UI chrome labels only (VI default, EN toggle).
// Sample/user-generated content stays Vietnamese regardless of language.

export const PAIRS = [
  ['Team / Nhóm', 'Team / Group'],
  ['Nhóm đang làm use case, để người đọc biết hỏi ai.', 'The team behind the use case, so readers know who to ask.'],
  ['Vai trò hoặc nhóm nào dùng được use case này.', 'Which role or team can use this.'],
  ['Các bước làm, viết sao cho người khác đọc là làm lại được.', 'The steps, written so someone else can repeat them.'],
  ['Cần chuẩn bị gì', 'What you need first'],
  ['CẦN CHUẨN BỊ GÌ', 'WHAT YOU NEED FIRST'],
  ['Công cụ, quyền truy cập, dữ liệu hoặc tài khoản cần có trước khi bắt đầu.', 'Tools, access, data or accounts needed before you start.'],
  ['Kết quả đạt được: thời gian tiết kiệm, chất lượng, số liệu nếu có.', 'What you got: time saved, quality, numbers if any.'],
  ['Giới hạn & lưu ý', 'Limits & notes'],
  ['GIỚI HẠN & LƯU Ý', 'LIMITS & NOTES'],
  ['Chỗ nào AI còn sai, dữ liệu nào không được đưa vào, cần người kiểm lại khâu nào.', 'Where AI still gets it wrong, what data must stay out, which steps need a human check.'],
  ['Link tài liệu / repo', 'Doc / repo link'],
  ['LINK TÀI LIỆU / REPO', 'DOC / REPO LINK'],
  ['Link tới tài liệu, repo hoặc file mẫu để người khác tự xem.', 'Link to the doc, repo or sample file so others can look themselves.'],
  ['Người liên hệ (PIC)', 'Contact (PIC)'],
  ['NGƯỜI LIÊN HỆ', 'CONTACT'],
  ['Ai trả lời khi người đọc gặp vướng.', 'Who answers when a reader gets stuck.'],
  ['Người thực hiện', 'Who built it'],
  ['NGƯỜI THỰC HIỆN', 'WHO BUILT IT'],
  ['Trạng thái', 'Status'],
  ['TRẠNG THÁI', 'STATUS'],
  ['Độ khó khi làm lại', 'How hard to repeat'],
  ['ĐỘ KHÓ', 'DIFFICULTY'],
  ['Required · chọn một', 'Required · pick one'],
  ['Ý tưởng', 'Idea'],
  ['Đang dùng thật', 'In production'],
  ['Dễ', 'Easy'],
  ['Trung bình', 'Medium'],
  ['Khó', 'Hard'],
  ['Còn thiếu thông tin bắt buộc — điền đủ các mục Required để người khác đọc là làm lại được.', 'Some required fields are missing — fill them all in so others can repeat this.'],
  ['Còn thiếu thông tin bắt buộc — điền đủ các mục Required trước khi gửi duyệt.', 'Some required fields are missing — fill them all in before submitting.'],
  ['Điền đủ các mục Required để người đọc hiểu và làm lại được. Admin duyệt trước khi publish.', 'Fill in every Required field so readers can understand and repeat it. Admin reviews before publishing.'],
  ['Trang chủ', 'Home'],
  ['Thư viện Use Case', 'Use Case Library'],
  ['Use Case', 'Use Cases'],
  ['Câu hỏi', 'Questions'],
  ['Hồ sơ', 'Profile'],
  ['Thông báo', 'Notifications'],
  ['Đánh dấu đã đọc tất cả', 'Mark all as read'],
  ['Đăng nhập bằng Microsoft 365', 'Sign in with Microsoft 365'],
  ['Đặt câu hỏi', 'Ask a Question'],
  ['Chia sẻ Use Case', 'Share a Use Case'],
  ['Use Case nổi bật', 'Featured Use Cases'],
  ['Xem tất cả use case', 'View all use cases'],
  ['Xem thêm use case', 'View more use cases'],
  ['Xem tất cả câu hỏi', 'View all Questions'],
  ['Xem tất cả team', 'View all teams'],
  ['Xem toàn bộ thư viện', 'Browse the full library'],
  ['Khám phá Thư viện Use Case', 'Explore Use Case Library'],
  ['Khám phá theo công việc của bạn', 'Explore by your work'],
  ['Khám phá ngay', 'Explore now'],
  ['Khám phá Prototype', 'Explore Prototypes'],
  ['Khám phá các AI prototype từ Claw-a-thon', 'Explore AI prototypes from the Claw-a-thon'],
  ['Câu hỏi đang chờ trả lời', 'Questions Waiting for Answers'],
  ['Đang chờ trả lời', 'Waiting for answers'],
  ['Không còn câu hỏi nào đang chờ', 'No questions are waiting'],
  ['Mở trong Questions', 'Open in Questions'],
  ['Hoạt động gần đây', 'Recent activity'],
  ['Đã lọc theo team:', 'Filtered by team:'],
  ['Xoá bộ lọc', 'Clear filters'],
  ['Tất cả', 'All'],
  ['Gần nhất', 'Most recent'],
  ['Mới nhất', 'Latest'],
  ['Hữu ích nhất', 'Most helpful'],
  ['Được nhiều vote nhất', 'Most voted'],
  ['Chờ trả lời', 'Unanswered'],
  ['Đã đăng', 'Posted by me'],
  ['Đã lưu', 'Saved'],
  ['Chi tiết câu hỏi', 'Question Details'],
  ['Tiêu đề câu hỏi', 'Question Title'],
  ['Nội dung', 'Details'],
  ['Bắt buộc', 'Required'],
  ['Không bắt buộc', 'Optional'],
  ['Bắt buộc · được chọn nhiều', 'Required · multiple allowed'],
  ['Bắt buộc · chọn đúng 1', 'Required · pick exactly 1'],
  ['Không bắt buộc · tối đa 3', 'Optional · up to 3'],
  ['Không bắt buộc · ảnh chụp màn hình, file mẫu', 'Optional · screenshots, sample files'],
  ['Chủ đề', 'Topics'],
  ['Công cụ AI', 'AI Tools'],
  ['Hình ảnh', 'Images'],
  ['Thêm hình ảnh', 'Add image'],
  ['Lưu nháp', 'Save as Draft'],
  ['Lưu nháp & đóng', 'Save draft & close'],
  ['Xoá nháp', 'Discard draft'],
  ['Đăng câu hỏi', 'Post Question'],
  ['Đăng câu trả lời', 'Post Answer'],
  ['Gửi bình luận', 'Post comment'],
  ['Gửi duyệt', 'Submit for Review'],
  ['Xem trước', 'Preview'],
  ['Gửi', 'Send'],
  ['Quay lại', 'Back'],
  ['Quay lại đầu trang', 'Back to top'],
  ['Quay lại chỉnh sửa', 'Back to editing'],
  ['Quay lại Use Case Library', 'Back to Use Case Library'],
  ['Về Library', 'Back to Library'],
  ['Xem thêm', 'Show more'],
  ['Xem Use Case', 'View Use Case'],
  ['Xem dự án', 'View project'],
  ['Xem trong My Posts', 'View in My Posts'],
  ['Đăng dưới tên thật:', 'Posted under your real name:'],
  ['Gõ @ để mention đồng nghiệp', 'Type @ to mention a colleague'],
  ['Mention gửi thông báo trong sản phẩm và qua Microsoft Teams.', 'Mentions notify in-product and via Microsoft Teams.'],
  ['Câu hỏi được đăng trực tiếp, không cần Admin duyệt.', 'Questions are published directly, no admin review needed.'],
  ['Use Case cần Admin duyệt trước khi publish.', 'Use Cases need admin review before publishing.'],
  ['Đã gửi để Admin duyệt', 'Submitted for admin review'],
  ['Chia sẻ ngay', 'Share now'],
  ['Copy Prompt', 'Copy prompt'],
  ['Prompt mẫu', 'Sample prompt'],
  ['File mẫu · tải xuống', 'Sample file · download'],
  ['Video demo', 'Demo video'],
  ['Link GitHub', 'GitHub link'],
  ['Link dùng thử agent', 'Try the agent'],
  ['Xem nhanh', 'Quick View'],
  ['Thử thách', 'The Challenge'],
  ['Hướng dẫn từng bước ✨', 'Step-by-step guide ✨'],
  ['Vai trò AI & Con người', 'AI & Human roles'],
  ['✨ AI làm gì?', '✨ What the AI does'],
  ['👤 Con người làm gì?', '👤 What the human does'],
  ['Yêu cầu & Lưu ý', 'Requirements & Notes'],
  ['Dành cho ai', 'Who it is for'],
  ['Thời gian setup', 'Setup time'],
  ['Giải quyết', 'Solves'],
  ['Công cụ', 'Tools'],
  ['Độ khó', 'Difficulty'],
  ['Tools / Account', 'Tools / Accounts'],
  ['Kỹ năng', 'Skills'],
  ['Dữ liệu', 'Data'],
  ['Lưu ý quan trọng', 'Important notes'],
  ['Vấn đề', 'Problem'],
  ['Giải pháp', 'Solution'],
  ['Giá trị', 'Value'],
  ['Kết quả', 'Result'],
  ['Mô tả', 'Description'],
  ['Dùng AI thế nào', 'How AI is used'],
  ['Do team tech', 'By tech'],
  ['Do team non-tech', 'By non-tech'],
  ['Người mới', 'Beginner'],
  ['hữu ích', 'helpful'],
  ['người thấy hữu ích', 'found this helpful'],
  ['bình luận', 'comments'],
  ['Use Cases đã lưu', 'Saved Use Cases'],
  ['Questions đã lưu', 'Saved Questions'],
  ['Chờ duyệt', 'Pending Review'],
  ['Duyệt Use Cases', 'Review Use Cases'],
  ['Lý do', 'Reason'],
  ['Hướng dẫn', 'Guidelines'],
  ['Cộng đồng AI', 'AI Community'],
  ['Không tìm thấy use case phù hợp. Thử từ khóa khác nhé.', 'No matching use case. Try another keyword.'],
  ['Use case thực tế. Quy trình thật.', 'Practical AI use cases. Real workflows.'],
  ['Xây dựng bởi', 'Built by'],
  ['Bạn đang vướng ở đâu với AI?', 'Where are you stuck with AI?'],
  ['Bạn đang dùng AI để giải quyết công việc hiệu quả hơn?', 'Using AI to work more effectively?'],
  ['Bạn có một AI use case hay workflow hữu ích?', 'Got a useful AI use case or workflow?'],
  ['Chia sẻ workflow & tài liệu liên quan của bạn', 'Share your workflow and related materials'],
  ['Chỉ mất 5-10 phút', 'Takes only 5-10 minutes'],
  ['Duyệt các workflow được chia sẻ bởi các team tại Zalopay.', 'Browse workflows shared by teams across Zalopay.'],
  ['Hỏi nhanh, trả lời thẳng vào việc. Người đặt câu hỏi chọn câu trả lời đã giải quyết được vấn đề.', 'Ask fast, answer to the point. The asker picks the answer that solved the problem.'],
  ['Đã có câu trả lời được chấp nhận', 'An answer has been accepted'],
  ['Chưa có câu trả lời. Câu trả lời đầu tiên thường giúp ích nhiều nhất.', 'No answers yet. The first answer usually helps the most.'],
  ['Chưa có câu trả lời. Câu trả lời đầu tiên thường giúp ích nhất.', 'No answers yet. The first answer usually helps the most.'],
  ['Đồng nghiệp đang chờ câu trả lời. Một câu trả lời ngắn cũng đủ giúp họ đi tiếp.', 'Colleagues are waiting. Even a short answer helps them move on.'],
  ['Mọi câu hỏi đều đã có người trả lời. Bạn có thể đặt câu hỏi mới bất cứ lúc nào.', 'Every question has an answer. You can ask a new one any time.'],
  ['Thử từ khoá ngắn hơn, hoặc tên công cụ AI như Claude, Gemini, Copilot.', 'Try a shorter keyword, or an AI tool name like Claude, Gemini, Copilot.'],
  ['Đã lưu nháp. Draft chỉ là tiện ích cá nhân, không phải trạng thái kiểm duyệt.', 'Draft saved. Drafts are personal only, not a review state.'],
  ['Hãy chia sẻ để cùng nhau học hỏi và tạo ra giá trị lớn hơn cho Zalopay.', 'Share it so we can learn together and create more value for Zalopay.'],
  ['Hãy chia sẻ để cùng nhau học hỏi và tạo ra giá trị lớn hơn cho Zalopay nhé!', 'Share it so we can learn together and create more value for Zalopay!'],
  ['Chia sẻ để giúp cộng đồng Starters cùng học hỏi và áp dụng!', 'Share it so the Starters community can learn and apply it!'],
  ['Không tìm thấy use case phù hợp. Thử đổi bộ lọc hoặc từ khóa khác nhé.', 'No matching use case. Try another filter or keyword.'],
  ['Không tìm thấy dự án phù hợp. Thử đổi hạng mục hoặc từ khóa khác nhé.', 'No matching project. Try another category or keyword.'],
  ['Những giải pháp AI ấn tượng được xây dựng trong Claw-a-thon của Zalopay Starters.', 'Standout AI solutions built during the Zalopay Starters Claw-a-thon.'],
  ['Phỏng vấn nhanh và giúp bạn viết lại theo template chuẩn', 'A quick interview that rewrites your draft into the standard template'],
  ['Phỏng vấn nhanh và giúp bạn trình bày lại một cách trự quan hơn', 'A quick interview that helps you present it more visually'],
  ['Use case của bạn được publish để mọi người cùng sử dụng', 'Your use case gets published for everyone to use'],
  ['Use case của bạn được publish để mọi người cùng khám phá', 'Your use case gets published for everyone to explore'],
  ['Preview — đây là cách use case hiển thị sau khi được duyệt.', 'Preview — this is how the use case looks once approved.'],
]

export const ATTR_PAIRS = [
  ['Ví dụ: QC / QE, team mobile', 'e.g. QC / QE, mobile team'],
  ['Ví dụ: Product Ops', 'e.g. Product Ops'],
  ['Ví dụ: tài khoản Claude nội bộ, quyền xem dashboard CSAT, file .csv export', 'e.g. internal Claude account, CSAT dashboard access, exported .csv'],
  ['Không đưa dữ liệu khách hàng chưa che vào prompt...', 'Do not put unmasked customer data into the prompt...'],
  ['Ví dụ: Thảo NT · Product Ops', 'e.g. Thao NT · Product Ops'],
  ['Lưu use case', 'Save use case'],
  ['Tìm use case, câu hỏi, công cụ AI...', 'Search use cases, questions, AI tools...'],
  ['Tìm câu hỏi, tác giả, công cụ...', 'Search questions, authors, tools...'],
  ['Tìm use case: PRD, báo cáo, phân tích dữ liệu, ...', 'Search use cases: PRD, reports, data analysis, ...'],
  ['Tìm dự án...', 'Search projects...'],
  ['Tìm một vấn đề, quy trình hoặc use case...', 'Search a problem, workflow or use case...'],
  ['Bối cảnh, cách bạn đã thử, và kết quả mong đợi...', 'Context, what you tried, and the outcome you expect...'],
  ['Viết bình luận về use case này...', 'Write a comment about this use case...'],
  ['Viết câu trả lời của bạn...', 'Write your answer...'],
  ['Viết câu trả lời của bạn. Gõ @ để mention đồng nghiệp.', 'Write your answer. Type @ to mention a colleague.'],
  ['Nhập category của bạn...', 'Enter your category...'],
  ['Nhập topic của bạn...', 'Enter your topic...'],
  ['Nhập công cụ AI của bạn...', 'Enter your AI tool...'],
]
